/*
 * Morphe patch for AI Plant Doctor (me.jodoin.aiplantdoctor)
 * Unlocks premium subscription features.
 *
 * Target: me.jodoin.aiplantdoctor v3.1.0 (antisplit)
 *
 * Flutter in_app_purchase_android Pigeon fingerprints.
 * The app is NOT obfuscated at the Flutter plugin level.
 * Class: io.flutter.plugins.inapppurchase.InAppPurchasePlugin (in classes4.dex)
 *
 * The Pigeon generated code registers each API method as a BasicMessageChannel.
 * We identify the relevant setup methods by their unique channel name strings.
 */

package app.morphe.patches.aiplantdoctor.premium

import app.morphe.patcher.Fingerprint

/**
 * Fingerprints the Pigeon setup method for queryPurchasesAsync.
 *
 * This method is generated by Pigeon inside InAppPurchaseApi class.
 * It creates a BasicMessageChannel with the string:
 *   "dev.flutter.pigeon.in_app_purchase_android.InAppPurchaseApi.queryPurchasesAsync"
 *
 * When called from Flutter, the Android side calls BillingClient.queryPurchasesAsync()
 * and sends the result back. We intercept this to always return a premium subscription.
 */
internal object QueryPurchasesAsyncSetupFingerprint : Fingerprint(
    strings = listOf(
        "dev.flutter.pigeon.in_app_purchase_android.InAppPurchaseApi.queryPurchasesAsync",
    ),
)

/**
 * Fingerprints the Pigeon callback method for onPurchasesUpdated.
 *
 * This is in InAppPurchaseCallbackApi - the reverse direction (Android -> Flutter).
 * When BillingClient detects a purchase update (e.g. after launchBillingFlow),
 * this sends the result back to Dart.
 *
 * Identified by:
 *   "dev.flutter.pigeon.in_app_purchase_android.InAppPurchaseCallbackApi.onPurchasesUpdated"
 */
internal object OnPurchasesUpdatedSetupFingerprint : Fingerprint(
    strings = listOf(
        "dev.flutter.pigeon.in_app_purchase_android.InAppPurchaseCallbackApi.onPurchasesUpdated",
    ),
)

/**
 * Fingerprints the startConnection Pigeon setup method.
 *
 * When Flutter calls startConnection, the Android plugin starts the BillingClient.
 * We inject a fake purchase event here so Flutter sees the subscription immediately
 * upon billing client initialization, before any queryPurchasesAsync calls.
 */
internal object StartConnectionSetupFingerprint : Fingerprint(
    strings = listOf(
        "dev.flutter.pigeon.in_app_purchase_android.InAppPurchaseApi.startConnection",
    ),
)
